print('=== Calculando a média do aluno ===')
nome = str(input('Nome do aluno:'))
materia = str(input('Informe a Materia:'))
curso = str(input('Curso: '))
n1 = float(input('Informe a nota do 1º Bimestre: '))
n2 = float(input('Informe a nota do 2º Bimestre: '))
n3 = float(input('Informe a nota do 3º Bimestre: '))
n4 = float(input('Informe a nota do 4º Bimestre: '))
print(' Aluno: {}.\n Matéria: {}.\n Curso: {}.\n'.format(nome,materia,curso))
print('Sua média foi {}.'.format(n1+n2+n3+n4/4))
