print('======== Aumento de Salário ========')
funcionario = str(input('Funcionário: '))
setor = str(input('Setor: '))
Funcao = str(input('Função: '))
salario = float(input('Salário: R$ '))
aumento = salario + (salario * 15/100)
print(' Funcionário: {}\n. Setor: {}\n. Função: {}\n.Seu salário era R$ {:.2f}\n, com o novo aumento de 15% seu salário foi para R$ {}.'.format(funcionario,setor,Funcao,salario,aumento))
print('='*36) 
